### ISSUE TITLE
And chapter after 3 not loading

### ISSUE THREAD

**Issue by sgu222e** [lhunath/guide.bash.academy#20]
Observed Issue: I have just completed reading chapter 3 (Variables and Expansions) (http://guide.bash.academy/03.variables.html#) and clicked the Next Up link to start chapter 4 (Tests and Conditionals) (http://guide.bash.academy/04.conditionals.html) but the page only loaded the the header section with a pound sign and what looks like a number 1 (#1)displaying where the normal content would be. I clicked on other chapters from the menu, only the home page and Chapter 1 through 3 loaded correctly.
In order to rule out a browser issue (Using Chrome Version 49.0.2623.75 beta-m (64-bit)), I also tried loading the pages  with Firefox, IE and Edge. All failed.
In order to eliminate network issues, I remote connected to an off network computer and tested with Chrome, IE and Edge. All failed. 

Desired Results: Having completed reading chapter 3 and clicking on the Next Up link, the content from chapter 4 should properly load. Other chapters should also load correctly in all popular internet browsers.

Steps to recreate:
1: load the Bash Guide: http://guide.bash.academy/
2: Complete chapters 1, 2 and 3 (optional I guess)
3: Try to load chapter 4 (or 5, 6, 7, 8, 9, 10 or 11)

Browsers used:
Chrome v49.0.2636.75 beta-m (64-bit)
Firefox 44.0.2
IE 11.0.9600.17801
Remote System
Chrome v48.0.2564.116 m
IE 11.103.10586.0
Edge 25.10586.0.0

**Comment by lhunath** [comment]
Unfortunately, I haven't yet found the time to write chapter 4 and up.  I recommend you star the page here to find out when these chapters become available.
