### ISSUE TITLE
Chapter-2 Command and Arguments might have an error in 'quoting literals' section.

### ISSUE THREAD

**Issue by phnxrbt** [lhunath/guide.bash.academy#23]
In the quoting literal section there is a warning box which has two examples, broken! and correct. But the broken! example looks broken because there is no space between /home/ and $username. So it is probably doing the same thing as the correct example .(i am new to bash so i might be wrong .)

**Comment by lhunath** [comment]
The broken example:

```rm -vr /home/$username```

Has no space in code, but there is a space inside the `username` variable.  As a result, the expansion looks like:

`rm` `-vr` `/home/` `lhunath`

Which results in `rm` being executed with two arguments: `/home/` and `lhunath` (no space in either argument - the space is used by bash to word-split the arguments).

In the good example:

```rm -vr "/home/$username"```

The resulting expansion is:

`rm` `-vr` `"/home/ lhunath"`

Which results in `rm` being executed with ONE argument: `/home/ lhunath` (there is a space in this argument - the double quotes ensure the space is literal data and not used by bash to word-split the arguments apart).
