### ISSUE TITLE
Will this be completed?

### ISSUE THREAD

**Issue by jerbaroo** [lhunath/guide.bash.academy#24]
Chapter 4-11 have no content and there hasn't been work on the project for a while. Think it would be a useful resource if completed, here showing my interest.

**Comment by Donkeyfish87** [comment]
+1

**Comment by SJern** [comment]
@barischj I know! I was totally excited while working chapter 1-3. So many things in the terminal that never made any sense are now clear as day! Please continue this guide.

**Comment by lhunath** [comment]
Sorry guys.  I have every intention of continuing this guide but life has taken an ironic turn and it's pretty hectic right now.  Eventually :–)

**Comment by SJern** [comment]
No worries. Although incomplete - it got me to a very good starting point. We really appreciate the effort you had put in!
