### ISSUE TITLE
EXPAN 5 solution

### ISSUE THREAD

**Issue by znicholls** [lhunath/guide.bash.academy#28]
I'm not sure why but when I ran the solution to exercise EXPAN 5 I got

$ echo "${greeting^}!"
-bash: !": event not found

However running 

$ echo "${greeting^*}! "
Hello world! 

is clearly fine. I'm running on scientific linux if that helps, I am happy to provide any other details that would be useful.

**Comment by lhunath** [comment]
This is due to a bash feature called "History Expansion" which only triggers on the interactive command prompt.  It's generally just a really annoying feature, and many people disable it.  I've patched the guide to avoid using an exclamation mark in double quotes because of this.  Thanks!

767a42b
