### ISSUE TITLE
How did you create these images?

### ISSUE THREAD

**Issue by mamachanko** [lhunath/guide.bash.academy#8]
- https://raw.github.com/lhunath/guide.bash.academy/gh-pages/img/inception.jpg
- https://github.com/lhunath/guide.bash.academy/blob/gh-pages/img/variables.jpg

**Comment by lhunath** [comment]
These images are a screenshot from a specifically configured http://www.secretgeometry.com/apps/cathode/

**Comment by mamachanko** [comment]
thanks @lhunath
