### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by prince-of-maroc** [lhunath/guide.bash.academy#82]
There hasn't been a commit in over 6 months. I hope that this project has not been abandoned..

**Comment by lhunath** [comment]
Hi @prince-of-maroc, unfortunately I am no longer actively writing the Bash guide since other priorities have taken forefront in life. I hope the content which exists has been valuable to you as a means of starting your journey. Keep in mind that the `man bash` is quite well written.

**Comment by prince-of-maroc** [comment]
I'm sad to hear that, but I wish you the best of luck with your other endeavours. 
As I understand it you will no longer be actively writing the guide, but will you still be reviewing/accepting pull requests?

**Comment by lhunath** [comment]
I am indeed still reviewing.
