### ISSUE TITLE
How do you know I donated?

### ISSUE THREAD

**Issue by wisdomlight** [lhunath/guide.bash.academy#87]
How do you know I actually donated?
Also - I have few remarks about the Inception part - especially when we are learning about the file descriptors.

**Comment by lhunath** [comment]
The web page simply remembers your action in local storage to show a thank-you message.
https://github.com/lhunath/guide.bash.academy/blob/gh-pages/js/main.js#L23

Of course your payment method, such as paypal, keeps its own records.

Feel free to leave a comment or suggestion, or open a PR for a proposal.

**Comment by wisdomlight** [comment]
But when I move to a different machine or browser - it will not know that I have donated.
Just a thought - maybe have a login for members?

**Comment by wisdomlight** [comment]
Where can I make comments on content?
For example in the inception chapter, this [graphics](https://guide.bash.academy/img/streams.png): its not clear what is the purpsoe of the  >&2 after the echo "Your name" 
It is also not clear how image 1 FD2 turns into image2 FD1
