### ISSUE TITLE
Can I get the original jekyll repo ?

### ISSUE THREAD

**Issue by fengzhao** [lhunath/guide.bash.academy#90]
I want to get the original jekyll repo and translate it into chinese fully . I hope to get your authorization

**Comment by lhunath** [comment]
Feel free to fork this repo, just take note of the license terms.

**Comment by fengzhao** [comment]
I really want the origin markdown  jekyll repo, not rendered into html , Could you please push the original repo branch to github ?

**Comment by lhunath** [comment]
This is the original, not rendered. Note that I am using html jekyll templates, not markdown ones.
